name: Binder-Main-Update

on:
  push:
    branches:
      - main
  
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update environment file
        run: |
          git checkout binder-main
          git checkout main binder/environment.yml
          git status
          if [ $(git diff-index binder-main | wc -l) -gt 0 ]; \ 
          then \
          git status; \
          git commit -m "update"; \
          git status; \ 
          git push origin binder-main; \
          git status; \
          fi